config {
  type: "operations",
  schema: "customer_orders_bronze",
  name: "customers",
  hasOutput: true
}

CREATE OR REPLACE EXTERNAL TABLE `behnaz-data-engineer-portfolio.customer_orders_bronze.customers`
(
  customer_id INT64,
  full_name STRING,
  email STRING,
  created_at TIMESTAMP
)
OPTIONS (
  format = 'CSV',
  uris = ['gs://behnaz-customer-orders/customers/*.csv'],
  skip_leading_rows = 1
)
