config {
  type: "operations",
  schema: "customer_orders_bronze",
  name: "orders",
  hasOutput: true
}

CREATE OR REPLACE EXTERNAL TABLE `behnaz-data-engineer-portfolio.customer_orders_bronze.orders`
(
  order_id INT64,
  customer_id INT64,
  order_date DATE,
  order_amount NUMERIC,
  status STRING
)
OPTIONS (
  format = 'CSV',
  uris = ['gs://behnaz-customer-orders/orders/*.csv'],
  skip_leading_rows = 1
)
